from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship
from database import Base


class Conversation(Base):
    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True)
    # Owner. NOT NULL and FK-enforced, set from the authenticated token, never
    # from the request body — same rule as trips.
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Generated by the model after the first exchange; null until then, and the
    # header shows "New chat" in the meantime.
    title = Column(String(256), nullable=True)
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # Bumped on every new message so the history list can order by recent
    # activity rather than creation time.
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    user = relationship("User", back_populates="conversations")
    # Ordered by id, not created_at: the user and assistant message of one turn
    # are inserted in the same transaction and share a created_at, so only the
    # serial id reliably keeps them user-then-assistant.
    messages = relationship(
        "Message",
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="Message.id",
    )
